---
deployment:
  tasks:
    - export DEPLOYPATH=/home/titudahu/public_html/
    - /bin/cp -R Assets $DEPLOYPATH
    - /bin/cp -R csv_files $DEPLOYPATH
    - /bin/cp -R DATABASE $DEPLOYPATH
    - /bin/cp -R gallery $DEPLOYPATH
    - /bin/cp -R gallery/edit $DEPLOYPATH
    - /bin/cp -R gallery/delete $DEPLOYPATH
    - /bin/cp -R home $DEPLOYPATH
    - /bin/cp -R home/edit $DEPLOYPATH
    - /bin/cp -R home/delete $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R protisthan $DEPLOYPATH
    - /bin/cp -R protisthan/edit $DEPLOYPATH
    - /bin/cp -R protisthan/delete $DEPLOYPATH
    

