---
deployment:
  tasks:
    - export DEPLOYPATH=/home/titudahu/public_html/
    - /bin/cp * $DEPLOYPATH
    - /bin/cp -R protisthan $DEPLOYPATH
    - /bin/cp -R protisthan/edit $DEPLOYPATH
    - /bin/cp -R protisthan/delete $DEPLOYPATH

